GET http://localhost:3003/progressAll HTTP/1.1
###
GET   http://localhost:3003/progressOne/1 HTTP/1.1
content-Type: application/json

{"id":1}
//entity id == payment id of card 1
###
POST http://localhost:3003/paymentSuccess HTTP/1.1
content-Type: application/json

{
  "entity": "event",
  "account_id": "acc_BFQ7uQEaa7j2z7",
  "event": "payment.captured",
  "contains": [
    "payment"
  ],
  "payload": {
    "payment": {
      "entity": {
        "id": "pl_Ms5Zau7auf7Cwv",
        "entity": "payment",
        "amount": 1000,
        "currency": "INR",
        "base_amount": 100,
        "status": "captured",
        "order_id": "order_DESxiijbl9xjDB",
        "invoice_id": null,
        "international": false,
        "method": "upi",
        "amount_refunded": 0,
        "amount_transferred": 0,
        "refund_status": null,
        "captured": true,
        "description": null,
        "card_id": null,
        "bank": null,
        "wallet": null,
        "vpa": "gaurav.kumar@upi",
        "email": "gaurav.kumar@example.com",
        "contact": "+919876543210",
        "notes": [],
        "fee": 2,
        "tax": 0,
        "error_code": null,
        "error_description": null,
        "error_source": null,
        "error_step": null,
        "error_reason": null,
        "acquirer_data": {
          "rrn": "0125836177"
        },
        "created_at": 1567675356,
        "upi": {
          "payer_account_type": "credit_card",
          "vpa": "gaurav.kumar@upi",
          "flow": "in_app"
        }
      }
    }
  },
  "created_at": 1567675356
}

###

POST http://localhost:3003/paymentSuccess HTTP/1.1
content-Type: application/json

{
  "entity": "event",
  "account_id": "acc_BFQ7uQEaa7j2z7",
  "event": "payment.captured",
  "contains": [
    "payment"
  ],
  "payload": {
    "payment": {
      "entity": {
        "id": "pay_DESyzxuld02Zul",
        "entity": "payment",
        "amount": 100,
        "currency": "INR",
        "base_amount": 100,
        "status": "captured",
        "order_id": "order_DESxiijbl9xjDB",
        "invoice_id": null,
        "international": false,
        "method": "upi",
        "amount_refunded": 0,
        "amount_transferred": 0,
        "refund_status": null,
        "captured": true,
        "description": null,
        "card_id": null,
        "bank": null,
        "wallet": null,
        "vpa": "gaurav.kumar@upi",
        "email": "gaurav.kumar@example.com",
        "contact": "+919876543210",
        "notes": [],
        "fee": 2,
        "tax": 0,
        "error_code": null,
        "error_description": null,
        "error_source": null,
        "error_step": null,
        "error_reason": null,
        "acquirer_data": {
          "rrn": "0125836177"
        },
        "created_at": 1567675356,
        "upi": {
          "payer_account_type": "credit_card",
          "vpa": "gaurav.kumar@upi",
          "flow": "in_app"
        }
      }
    }
  },
  "created_at": 1567675356
}