name: Development

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: 'dev'

      - name: Install Packages & Setup
        run: |
          cd dev/
          npm ci

      - name: Build
        run: |
          cd dev/
          npm run build

      - name: Restart Services
        run: sudo pm2 restart weddingFrontEnd
